---
language: node_js
node_js:
  - "4"
  - "6"
  - "7"

sudo: false

cache:
  directories:
    - $HOME/.npm

matrix:
  fast_finish: true

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^4"

install:
  - npm install

script:
 - npm test
